FROM node:20-alpine AS builder

RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm turbo run build --filter=@elecshop/web

FROM node:20-alpine AS runner

RUN corepack enable

WORKDIR /app

COPY --from=builder /app .

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["pnpm", "--filter=@elecshop/web", "start"]