name: Build and Push Images

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  WEB_IMAGE: elecshop-web
  SERVER_IMAGE: elecshop-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm turbo run lint
        continue-on-error: true

      - name: Run Tests
        run: pnpm turbo run test
        continue-on-error: true

      - name: Build Workspace
        run: pnpm turbo run build

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} \
          --username "${{ secrets.AZURE_REGISTRY_USERNAME }}" \
          --password-stdin

      - name: Build Web Docker Image
        run: |
          docker build \
          -f web/Dockerfile \
          -t $REGISTRY/$WEB_IMAGE:${{ github.sha }} \
          -t $REGISTRY/$WEB_IMAGE:latest \
          .

      - name: Push Web Docker Image
        run: |
          docker push $REGISTRY/$WEB_IMAGE:${{ github.sha }}
          docker push $REGISTRY/$WEB_IMAGE:latest

      - name: Build Server Docker Image
        run: |
          docker build \
          -f server/Dockerfile \
          -t $REGISTRY/$SERVER_IMAGE:${{ github.sha }} \
          -t $REGISTRY/$SERVER_IMAGE:latest \
          .

      - name: Push Server Docker Image
        run: |
          docker push $REGISTRY/$SERVER_IMAGE:${{ github.sha }}
          docker push $REGISTRY/$SERVER_IMAGE:latest

      - name: Display Published Images
        run: |
          echo "Published:"
          echo "$REGISTRY/$WEB_IMAGE:${{ github.sha }}"
          echo "$REGISTRY/$WEB_IMAGE:latest"
          echo "$REGISTRY/$SERVER_IMAGE:${{ github.sha }}"
          echo "$REGISTRY/$SERVER_IMAGE:latest"